version: "3"

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: lnmp-mysql
    tty: true
    restart: always
    volumes:
      # - ./mysql/mysql-data:/var/lib/mysql
      # - ./mysql/mysql-logs:/var/log/mysql
      - my-data-mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: borer
    ports: 
      - "3306:3306"
    # networks:
      # - lnmp-networks


  php:
    image: devilbox/php-fpm:7.4-work
    container_name: lnmp-php
    tty: true
    restart: always
    volumes:
      - ./www:/var/www/html:rw
      # - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      # - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      # - ./php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    # networks:
      # - lnmp-networks
        # ipv4_address: 101.11.11.10

  nginx:
    build: ./nginx
    container_name: lnmp-nginx
    volumes:
      - ./www:/usr/share/nginx/html:rw
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    tty: true
    restart: always
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"
      - "8002:8002"
    depends_on:
      - php
    # networks:
      # - lnmp-networks
        # ipv4_address: 101.11.11.11

  # php:
    # build:
      # context: ./php
      # dockerfile: Dockerfile
    # container_name: lnmp-php
    # tty: true
    # restart: always
    # volumes:
      # - ./tp:/var/www
      # - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      # - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      # - ./php/php.ini:/usr/local/etc/php/php.ini
    # ports:
      # - "9000:9000"
    # networks:
      # - lnmp-networks
        # ipv4_address: 101.11.11.10
# networks:
  # lnmp-networks:
volumes:
  my-data-mysql:
  
