version: "3.8"

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: app-images-lnmp-mysql
    tty: true
    restart: always
    volumes:
      - lnmp-mysql-data:/var/lib/mysql:rw
      - ./mysql/mysql-logs:/var/log/mysql:rw
      # - my-data-mysql:/var/lib/mysql
      - /home/borer/compony/juli_oa_com.sql:/home/juli.sql
    environment:
      # MYSQL_ROOT_NAME: oa_test_com
      MYSQL_ROOT_PASSWORD: borer
    ports:
      - "3306:3306"
    networks:
      - lnmp-networks

  php8:
    build:
      context: ./php/php8
      dockerfile: Dockerfile
    container_name: app-images-lnmp-php8
    tty: true
    restart: always
    volumes:
      - ./www:/var/www/html:rw
      # - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      # - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/php.ini:/etc/php8/php.ini
    # ports:
      # - "9001:9001"
    networks:
      - lnmp-networks
        # ipv4_address: 101.11.11.10
    depends_on:
      - mysql

  php7:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app-images-lnmp-php7
    tty: true
    restart: always
    volumes:
      - ./www:/var/www/html:rw
      # - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      # - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      # - ./php/php.ini:/usr/local/etc/php/php.ini
    # ports:
      # - "9000:9000"
    depends_on:
      - mysql
    networks:
      - lnmp-networks

  nginx:
    build: ./nginx
    container_name: app-images-lnmp-nginx
    volumes:
      - ./www:/usr/share/nginx/html:rw
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    tty: true
    restart: always
    ports:
      - "80:80"
      # - "443:443"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    depends_on:
      - php7
      - php8
      - mysql
    networks:
      - lnmp-networks
        # ipv4_address: 101.11.11.11

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.0.2
      container_name: app-images-phpmyadmin
      environment:
          PMA_HOST: mysql
          # PMA_PORT: 3306
       # - PMA_ABSOLUTE_URI = https://my.domain.tld/phpmyadmin/
          # MYSQL_ROOT_PASSWORD: borer
      volumes:
        - lnmp-phpmyadmin:/var/www/html/
      networks:
        - lnmp-networks
      ports:
        - "8080:80"
      depends_on:
        - mysql

  redis:
      image: 'redis:6.2.6'
      container_name: app-images-redis
      ports:
         - '6379:6379'
      # volumes:
          # - 'sailredis:/data'
      networks:
          - lnmp-networks
      depends_on:
          - php7
          - php8
      healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s

networks:
  lnmp-networks:
volumes:
  lnmp-phpmyadmin:
  lnmp-mysql-data:
