version: "3.8"

services:
  mysql:
    build:
      context: ./mysql
      dockerfile: Dockerfile
    container_name: app-images-lnmp-mysql
    tty: true
    restart: always
    volumes:
      - lnmp-mysql-data:/var/lib/mysql:rw
      - ./mysql/mysql-logs:/var/log/mysql:rw
      # - my-data-mysql:/var/lib/mysql
      - /home/borer/compony/juli_oa_com.sql:/home/juli.sql
    environment:
      # MYSQL_ROOT_NAME: oa_test_com
      MYSQL_ROOT_PASSWORD: borer
    ports:
      - "3306:3306"
    networks:
      - lnmp-networks

  php8:
    build:
      context: ./php/php8
      dockerfile: Dockerfile
    container_name: app-images-lnmp-php8
    tty: true
    restart: always
    volumes:
      - ./www:/var/www/html:rw
      # - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      # - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      - ./php/php.ini:/usr/local/etc/php/php.ini
    # ports:
      # - "9001:9001"
    networks:
      - lnmp-networks
        # ipv4_address: 101.11.11.10
    depends_on:
      - mysql

  php7:
    build:
      context: ./php
      dockerfile: Dockerfile
    container_name: app-images-lnmp-php7
    tty: true
    restart: always
    volumes:
      - ./www:/var/www/html:rw
      # - ./php/php-fpm.conf:/usr/local/etc/php-fpm.conf
      # - ./php/php-fpm.d:/usr/local/etc/php-fpm.d
      # - ./php/php.ini:/usr/local/etc/php/php.ini
    # ports:
      # - "9000:9000"
    depends_on:
      - mysql
    networks:
      - lnmp-networks

  nginx:
    build: ./nginx
    container_name: app-images-lnmp-nginx
    volumes:
      - ./www:/usr/share/nginx/html:rw
      # - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf:rw
    tty: true
    restart: always
    ports:
      - "80:80"
      # - "443:443"
      - "8001:8001"
      - "8002:8002"
      - "8003:8003"
    depends_on:
      - php7
      - php8
      - mysql
    networks:
      - lnmp-networks
        # ipv4_address: 101.11.11.11

  phpmyadmin:
      image: phpmyadmin/phpmyadmin:5.0.2
      container_name: app-images-phpmyadmin
      environment:
          PMA_HOST: mysql
          # PMA_PORT: 3306
       # - PMA_ABSOLUTE_URI = https://my.domain.tld/phpmyadmin/
          # MYSQL_ROOT_PASSWORD: borer
      volumes:
        - lnmp-phpmyadmin:/var/www/html/
      networks:
        - lnmp-networks
      ports:
        - "8080:80"
      depends_on:
        - mysql

  redis:
      image: 'redis:6.2.6'
      container_name: app-images-redis
      ports:
         - '6379:6379'
      # volumes:
          # - 'sailredis:/data'
      networks:
          - lnmp-networks
      depends_on:
          - php7
          - php8
      healthcheck:
          test: ["CMD", "redis-cli", "ping"]
          retries: 3
          timeout: 5s

  # wechat-devtools:
      # image: 'canyoutle/wxdt'
      # container_name:  wxdt
      # volumes:
        # - $HOME/wechat-projects:/projects
      # ports:
        # - 6080:80
      # networks:
        # - lnmp-networks

  # devtools:
    # image: sigoden/wechat-devtools
    # volumes:
      # - /tmp/.X11-unix:/tmp/.X11-unix
      # - $HOME/.config/wechat-dev-tools:/home/node/.config/微信web开发者工具
      # - $HOME/weapp:/home/node/weapp
    # environment:
      # - DISPLAY=$DISPLAY
      # - LANG=zh_CN.UTF-8 # 可选 默认zh_CN
      # - GID=$GID # 可选 默认1000 主机当前用户 gid 解决挂载目录访问权限问题
      # - UID=$UID # 可选 默认1000 主机当前用户 uid 解决挂载目录访问权限问题

networks:
  lnmp-networks:
volumes:
  lnmp-phpmyadmin:
  lnmp-mysql-data:
